### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by shinya2020** [shinya2020/furima-30435#9]
#自身のフリマアプリのURL
https://furima-30435.herokuapp.com/

#Basic認証のID
admin
#Basic認証のパスワード
furima-30435

#出品者用のメールアドレス
test@test
#出品者用のパスワード
test1234

#購入者用のメールアドレス
test2@test
#購入者用のパスワード
test1234

#購入用カードの番号
4242424242424242
#購入用カードの期限 
2023年3月
#購入用カードのセキュリティコード
123

ご確認よろしくお願いします！

**Comment by tnk1215** [comment]
ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
